apiVersion: v1
clusters:
- cluster:
    server: https://10.96.0.1:6443
  name: default-cluster
- cluster:
    certificate-authority-data: REDACTED
    server: https://192.168.58.134:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
