FROM phusion/baseimage:0.9.22

CMD ["/sbin/my_init"]

USER root
RUN apt-get update && apt-get install -y curl \
    wget \
    sudo
RUN wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
RUN echo deb http://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list
RUN apt-get update && sudo apt-get install -y docker jenkins 

RUN ufw allow 8080

RUN apt-get update && apt-get install -y apt-transport-https
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
RUN apt-get update
RUN apt-get install -y kubelet